Lts 8 9
lequal/sonarqube pull request #33
Opened 2022-03-16 16:36 UTC by gbonnefille

## Proposed changes
Move to SonarQube 8.9

## Types of changes

What types of changes does your code introduce to this project?
> _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Issues closed by changes

- [x] Close #31 

## Checklist

> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I agree with the [CODE OF CONDUCT](CODE_OF_CONDUCT.md)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-14 06:50 UTC, gbonnefille commented
The Usine Logicielle from CNES give me the list of selected plugins and versions.

Plugin | Description | Version prod
-- | -- | --
Checkstyle | Analyze Java code with Checkstyle | 8.40
Clover | Get code coverage with http://openclover.org/ | 4.1
SonarQube CNES Report | CNES app/plugin for SonarQube that allows users to export analysis reports as OpenXML, Markdown and CSV. | 4.0.0
Cobertura | Get code coverage with <a href="http://cobertura.sourceforge.net/">Cobertura</a>. | 2.0
Community Branch Plugin | Enables branch and pull request analysis in SonarQube Community Edition, without having to upgrade to Developer Edition | 1.8.1
C++ (Community) | Enable analysis and reporting on c++ projects. | 1.3.2 (build 1853)
Findbugs | Analyze Java, Scala, Closure and JSP code with SpotBugs. 4.0.0 | 4.0.4
Sonar Frama-C plugin | Frama-c plugin for Sonarqube | 2.1.1
Sonar i-Code CNES plugin | i-Code CNES plugin for SonarQube | 2.0.2
PMD | Analyze Java code with PMD. | 3.3.1
SonarTS | Code Analyzer for TypeScript | 2.1 (build 4359)
SonarQube Hadolint Plugin | Hadolint plugin for SonarQube | 1.0.0
Gcov | Import Gcov code coverage reports | 1.4.0
Modelsim | Get code coverage with Modelsim</a>. | 1.6.0
VHDL | Parent pom of SonarSource public projects | 3.4
FPGA metrics plugins | Import custom FPGA metrics | 1.3.0
Ansible Lint | Ansible lint plugin for SonarQube | 2.5.1
YAML Analyzer | YAML 1.1 plugin for SonarQube | 1.7.0

<br class="Apple-interchange-newline">

2022-07-01 15:18 UTC, gbonnefille commented
The Docker is now fully updated with compliant plugins.
I still expect official acknowledge to pulish here (under GPLv3) the new profiles.

@begarco can you give my any acknowledgement, please?

2023-01-05 12:13 UTC, gbonnefille commented
@diegorodriguez31 can you give me an acknoledgement to publish the profiles created by CNES and retrieve by us?
If OK, I propose to publish the files I have in this PR in order to let you review exactly what we are talking about.

2023-03-30 10:07 UTC, diegorodriguez31 commented
> @diegorodriguez31 can you give me an acknoledgement to publish the profiles created by CNES and retrieve by us? If OK, I propose to publish the files I have in this PR in order to let you review exactly what we are talking about.

Can you tell me more about these profiles?

2023-03-30 11:33 UTC, gbonnefille commented
> > @diegorodriguez31 can you give me an acknoledgement to publish the profiles created by CNES and retrieve by us? If OK, I propose to publish the files I have in this PR in order to let you review exactly what we are talking about.
> 
> Can you tell me more about these profiles?

I'm thinking about the profiles prepared by CNES for many languages, classified A, B, C or D and related to RNC CNES.

2023-03-30 11:36 UTC, diegorodriguez31 commented
> > > @diegorodriguez31 can you give me an acknoledgement to publish the profiles created by CNES and retrieve by us? If OK, I propose to publish the files I have in this PR in order to let you review exactly what we are talking about.
> > 
> > 
> > Can you tell me more about these profiles?
> 
> I'm thinking about the profiles prepared by CNES for many languages, classified A, B, C or D and related to RNC CNES.

Ok, can I handle it ? I already have all the configuration ready to be updated.

2023-03-30 11:48 UTC, gbonnefille commented
> > > > @diegorodriguez31 can you give me an acknoledgement to publish the profiles created by CNES and retrieve by us? If OK, I propose to publish the files I have in this PR in order to let you review exactly what we are talking about.
> > > 
> > > 
> > > Can you tell me more about these profiles?
> > 
> > 
> > I'm thinking about the profiles prepared by CNES for many languages, classified A, B, C or D and related to RNC CNES.
> 
> Ok, can I handle it ? I already have all the configuration ready to be updated.

Oh yes. Please, do it.

2023-04-05 12:31 UTC, diegorodriguez31 commented
Close #31

2023-04-06 13:31 UTC, gbonnefille commented
@diegorodriguez31 I'm seing a lot of changes in this PR. I would suggest to keep this PR focussed on publishing one version of the solution compatible with SonarQube 8.9.

Then, it will be possible to do more changes in other PR / versions. If gcov is deprecated, perhaps publishing a new version called 8.9-1 or something like that.

As said in OSS: release early, release often.

2023-04-07 12:25 UTC, diegorodriguez31 commented
@louisjdmartin pour review

2023-04-11 07:34 UTC, diegorodriguez31 commented
> 

Thank you for your comment. You are right I should have publish this PR earlier but all the changes here are the minimum change so that de 8.9 image works properly.

At this state, no modification will be done anymore.

2023-04-11 07:34 UTC, diegorodriguez31 commented
> @diegorodriguez31 I'm seing a lot of changes in this PR. I would suggest to keep this PR focussed on publishing one version of the solution compatible with SonarQube 8.9.
> 
> Then, it will be possible to do more changes in other PR / versions. If gcov is deprecated, perhaps publishing a new version called 8.9-1 or something like that.
> 
> As said in OSS: release early, release often.

Thank you for your comment. You are right I should have publish this PR earlier but all the changes here are the minimum change so that de 8.9 image works properly.

At this state, no modification will be done anymore.

2023-04-11 08:30 UTC, louisjdmartin reviewed
Le code semble ok pour moi
Je vais lancer l'image et faire quelques tests avant d'approuver définitivement la MR

2023-04-11 08:30 UTC, louisjdmartin commented on scripts/utils/compare_qp.bash
> +#!/usr/bin/env bash
Plutot cool de donner des scripts d'utils, c'est toujours utile, cependant il est d'usage de passer les fichiers en paramètres + variable d'env (pour le token). C'est toujours un peu dangereux les `read`

`SONAR_TOKEN=<token> ./compare_qp.bash http://localhost:9001 QP1 QP2`

Eventuellement en début de fichier tu peux ajouter un commentaire qui indique que c'est un script utilitaire sans garantie de fonctionnement ==> https://opensource.guide/notices/#legal-disclaimer

2023-04-14 08:41 UTC, gbonnefille commented on scripts/utils/compare_qp.bash
> +#!/usr/bin/env bash
J'avoue être un peu dubitatif sur l'intérêt d'embarquer cet utilitaire dans l'image SonarQube.

Dans ma compréhension, le dépôt Git courant a pour objet de faire fonctionner un service. Les utilitaires interactifs qui fonctionnent à distance du service seraient sans doute plus accessibles via un dépôt Git dédié du genre `sonarqube-utils`. Qui plus est, ce dépôt annexe pourra alors recevoir des README pour introduire l'usage des différents scripts.

2023-04-24 07:56 UTC, louisjdmartin requested changes

2023-04-24 07:56 UTC, louisjdmartin commented on Dockerfile
> +       jq
Il faut garder le `rm -rf <...>`. Il permet de réduire la taille de l'image docker !

On a plus besoin du lien symbolique ?

2023-04-24 07:56 UTC, louisjdmartin commented on scripts/utils/compare_qp.bash
> +#!/usr/bin/env bash
Effectivement, un dépot séparé sera peut-être plus propre.
@diegorodriguez31 on fera la création d'un dépot d'utilitaire.

2023-04-24 08:52 UTC, gbonnefille commented on Dockerfile
> +       jq
> On a plus besoin du lien symbolique ?

La logique a changé pour privilégier un javaagent : https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/1.8.1#installation

2023-04-24 08:57 UTC, louisjdmartin commented on Dockerfile
> +       jq
Ok c'est noté.

Pour la première partie de mon commentaire je réalise qu'on est passé d'apt à apk... c'est donc ok à ce niveau là aussi

2023-04-26 13:28 UTC, louisjdmartin requested changes
Juste le numéro de version a mettre à jour et c'est ok pour moi

2023-04-26 13:28 UTC, louisjdmartin commented on README.md
Ligne 17: C'est pas a jour ! Il faut incrémenter la version

2023-05-02 05:35 UTC, merged